---
- name: apply the common config to all
  hosts: all
  remote_user: root
  become: no

  roles:
  - common
  - vbox

- name: apply the web
  hosts: web
  remote_user: ansibleuser
  become: yes

  roles:
  - apache
  - web

- name: Jenkins host
  hosts: jenkins
  remote_user: ansibleuser
  become: yes

  roles:
  - jenkins
