---
# tasks file for elk_indexer

- name: Add elastic repo
  yum_repository:
    name: elasticrepo
    description: Repo for elastic products
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    file: elastic

- name: Install kibana
  yum: name=kibana state=present

- name: Copy kibana configs
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml
  notify: restart kibana

- name: Start kibana
  service: name=kibana state=started enabled=yes

- name: Check if Cerebro exists
  stat: path={{ cerebro_path }}/cerebro-{{ cerebro_ver }}/bin/cerebro
  register: cerebro_exists

- name: Download and unpack Cerebro
  unarchive:
    src: "https://github.com/lmenezes/cerebro/releases/download/v{{ cerebro_ver }}/cerebro-{{ cerebro_ver }}.tgz"
    dest: "{{ cerebro_path }}/"
    keep_newer: yes
    copy: no
  when: cerebro_exists.stat.exists == False

- name: install supervisor
  yum: name=supervisor state=present

- name: copy supervisor configs
  template: src={{ item }}.j2 dest=/etc/supervisord.d/{{ item }}
  with_items:
    - supervisor-cerebro.ini
  notify: restart supervisor

- name: copy cerebro configs
  template: src=cerebro.conf.j2 dest={{ cerebro_path }}/cerebro-{{ cerebro_ver }}/conf/application.conf
  notify: restart supervisor

- name: start supervisor
  service: name=supervisord state=started enabled=yes
