---
- name: Install nginx
  yum: name=nginx state=present

- name: Add nginx config file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Start nginx
  service: name=nginx state=started enabled=yes
