---
# tasks file for common

- include: selinux.yml

- name: install epel
  yum: 
    name=epel-release 
    state=latest

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: send root key for mbp
  authorized_key: user=root
    key="{{ lookup('file', 'root.pub') }}"
    path='/root/.ssh/authorized_keys'
    manage_dir=no

- include: ntp.yml
- include: ansible_user.yml
